### ISSUE TITLE
Missing modules, release not found

### ISSUE THREAD

**Issue by Humblehound** [testcontainers/testcontainers-scala#103]
Hi,

I've noticed that release `0.35.0` is present in the Readme but it's not published on Maven central. The release notes mention that missing modules have been added, I hope that's the case because the `rabbitmq` module is not found for version `0.34.3`. 

How are the packages published? Is there a way for me to help getting the modules published? Please let me know once the release is available

**Comment by dimafeng** [comment]
`0.35.0` should be available now
