### ISSUE TITLE
Get https://quay.io/v2/  request canceled while waiting for connection

### ISSUE THREAD

**Issue by nemoo** [testcontainers/testcontainers-scala#104]
This is more a question about documentation / how to.

In my testcase, I am currently instantiating the container via 
`override val container = PostgreSQLContainer(dockerImageNameOverride = "dockerio.bin.t-mobile.at/postgres:11.0")
`

When running testcontainers, I get the exception: 
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

Since this dependency is only reachable via a private repository for me, I guess I would need to overwrite "getRyukImage" in https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java  somehow to point to my private repository. 

How can I override this configuration to point  to my private repository?

**Comment by LMnet** [comment]
Try to create `testcontainers.properties` file in your resources and add `ryuk.container.image` property to it with your custom image address.

**Comment by nemoo** [comment]
thanks! that works perfectly!
