### ISSUE TITLE
hooks in the new API

### ISSUE THREAD

**Issue by quiquedev** [testcontainers/testcontainers-scala#121]
when using the posgresql container and the new testcontainers-scala API get the configuration of the container (jdbcURL, username and password) only when you are running the tests

the `beforeStop()` and `afterStart()` hooks are not there any more

i would like to use the `TestConainterForAll` trait and still being able to run a `after-start` hook to prepare the posgresql database (run some flyway migration) before start running the tests.

is it possible at the moment?

**Comment by LMnet** [comment]
Hi @quiquedev. There are `afterContainersStart` and `beforeContainersStop` methods for that.

**Comment by quiquedev** [comment]
hey @LMnet thanks for the quick answer :) i saw that already but not sure how to use in the following example:

```
class UserUsecasesSpec extends AnyFlatSpec with Matchers with TestContainerForAll {
  
  override val containerDef: ContainerDef = PostgreSQLContainer.Def()

  override def afterContainersStart(containers: Containers): Unit = {
    ???
  } 
```
`Containers` gives you a `forAll` method to iterate over `Stoppable` to manage the containers but what i would like to get in the hook is the jdbdURL, username and password of the postgresql container i defined. how would you do that?

**Comment by LMnet** [comment]
If you check `TestContainerForAll` implementation you will notice this:
```scala
final override type Containers = containerDef.Container
```
So, for your case `Containers` type is type alias for the `PostgreSQLContainer` type. And you can implement `afterContainersStart` like this:
```scala
override def afterContainersStart(container: PostgreSQLContainer): Unit = {
  super.afterContainersStart(container)
  ??? // your logic here
}
```

**Comment by quiquedev** [comment]
does it compile for you? i get:

```
[error]  found   : com.dimafeng.testcontainers.PostgreSQLContainer
[error]  required: UserUsecasesSpec.this.Containers
[error]     (which expands to)  UserUsecasesSpec.this.containerDef.Container
[error]     super.afterContainersStart(container)
```

**Comment by LMnet** [comment]
Hm, you are right. Looks like scala compiler can't infer that these types are equivalent.

Anyway, you can use pattern matching:
```scala
import com.dimafeng.testcontainers.{ContainerDef, PostgreSQLContainer}
import com.dimafeng.testcontainers.scalatest.TestContainerForAll
import org.scalatest.FlatSpec

class UserUsecasesSpec extends FlatSpec with TestContainerForAll {

  override val containerDef: ContainerDef = PostgreSQLContainer.Def("postgres:12")

  override def afterContainersStart(container: Containers): Unit = {
    super.afterContainersStart(container)
    container match {
      case _: PostgreSQLContainer => println("your logic here")
    }
  }

  "test" should "work" in withContainers { case postgreSQLContainer: PostgreSQLContainer =>
    succeed
  }
}
```
I tried this and it works.

**Comment by quiquedev** [comment]
which version of scalaTest are you using?

**Comment by LMnet** [comment]
3.0.8. In 3.1.0 some API slightly changes and my code may not compile as-is if you are using newer versions. But it doesn't really matter — that's just what I have at hand and testcontainers could work with any of this version.

**Comment by quiquedev** [comment]
i see, thanks a lot for your help. with your approach it seems to finally compile

**Comment by quiquedev** [comment]
https://github.com/testcontainers/testcontainers-scala/pull/122
