### ISSUE TITLE
Add support for AWS sdk v2 for localstack containers

### ISSUE THREAD

**Issue by jbwheatley** [testcontainers/testcontainers-scala#135]
The v2 sdk is a major rewrite of the java sdk (see here https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html). It would be great to be able to use testcontainers-scala to test integrations with this new sdk, in the same way demonstrated here for testcontainers-java: https://www.testcontainers.org/modules/localstack/

Happy to put together a PR!

**Comment by dimafeng** [comment]
Hey @jbwheatley,
Curious if it would make sense to implement in testcontainers-java so it becomes available in scala out of the box?

**Comment by jbwheatley** [comment]
I think part of the problem with that is that the localstack module has dependency `"com.amazonaws" % "aws-java-sdk-s3" % aswVersion % "provided", so if I update my sdk version to v2, (which is a completely different import `"software.amazon.awssdk" % "s3" % v2Version`), then you get `NoClassDefFoundError`s. 

The underlying java container already has the API necessary to set up my tests, but it won't run:
```
A needed class was not found. This could be due to an error in your runpath. Missing class: com/amazonaws/auth/AWSCredentials
java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials
```

**Comment by dimafeng** [comment]
Oh, I see what you mean! I thought the problem is in the java version and the scala version just inherits it.
A PR would be appreciated!
