### ISSUE TITLE
Address image compatibility checks in Scala API

### ISSUE THREAD

**Issue by pbylicki** [testcontainers/testcontainers-scala#139]
Hi,
As it was mentioned in the comments under #133, switching to version 1.15.0 of testcontainers-java introduces image compatibility checks, that require images with non-default names to be explicitly set as compatible:
https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.0-rc2
It can be easily handled using Java API by using `DockerImageName`-based constructors for Containers, but Scala API for Containers uses only `String` parameters.

I would be happy to contribute, but would like to understand how is Scala API supposed to address that.
Setting image as compatible by default is rather against the path set by testcontainers-java.
Other potential solutions would be to 
- change `dockerImageNameOverride` type to `Option[DockerImageName]` in Container classes so it can be initialized either as usual by String (mapped to `DockerImageName` in `apply`) or by `DockerImageName` with explicit compatibility set.
- add flag to each container class that could be used to resolve if image should be marked as compatible.

Let me know what's your opinion.

**Comment by dimafeng** [comment]
@pbylicki I think "change dockerImageNameOverride type to Option[DockerImageName]" is the right option

@LMnet, what do you think?

**Comment by LMnet** [comment]
I think it's ok, but we should not forget about backward compatibility. Old style constructors should be supported too but marked as deprecated (like in testcontainers-java).
