### ISSUE TITLE
Is reuse.enable supported?

### ISSUE THREAD

**Issue by nacorti** [testcontainers/testcontainers-scala#168]
We have a heavy container setup, and would like to be able to reuse the same containers for all of our tests. I notice that the java lib provides `testcontainers.reuse.enable`, but when I try to turn on reuse via config file, it fails silently.

Using testcontainers-scala 0.38.4, which should pull in testcontainers-java [1.14.3](https://github.com/testcontainers/testcontainers-java/releases/tag/1.14.0), which has [reusable containers](https://github.com/testcontainers/testcontainers-java/pull/1781)

My .testcontainers.properties
`#Modified by Testcontainers
#Wed Mar 10 17:36:09 CST 2021
docker.client.strategy=org.testcontainers.dockerclient.UnixSocketClientProviderStrategy
testcontainers.reuse.enable=true`

I've tried setting the property by ~/.testcontainers.properties, Classpath, and Env per docs, but with no log warnings or errors re reuse, I'm not sure how I should proceed from here.

Thank you in advance!

**Comment by dimafeng** [comment]
Hi @nacorti, you can check this for more details https://github.com/testcontainers/testcontainers-scala/issues/160
