### ISSUE TITLE
Test container not picking up migration file.

### ISSUE THREAD

**Issue by SarpongAbasimi** [testcontainers/testcontainers-scala#176]
Hey 👋,

I am working on a Scala project and would like to use Testcontainers to test database migration.
The problem I am currently facing is that the migration file is not being picked up by Testcontainers.

      Class.forName(container.driverClassName)
      val connection = DriverManager.getConnection(
        container.jdbcUrl,
        container.username,
        container.password
      )
Do I need any special config for this to happen?

**Comment by LMnet** [comment]
Hi @SarpongAbasimi 

Could you give more details? How do you create your containers? Where are your migrations? How do you expect them to work?

**Comment by SarpongAbasimi** [comment]
@LMnet I create my containers using

```
  Class.forName(container.driverClassName)
  val connection = DriverManager.getConnection(
    container.jdbcUrl,
    container.username,
    container.password
  )
```
Maybe I am not clear on how Testcontainers works, If you could explain it to me that will be great.

**Comment by LMnet** [comment]
@SarpongAbasimi this code does not seem related to the testcontainers and to your question. At this moment I could only suggest you read the documentation of testcontains-scala and testcontainers-java.

**Comment by SarpongAbasimi** [comment]
@LMnet  the code is from here 
Link - https://github.com/testcontainers/testcontainers-scala

Have a look at the `Postgres section`.

I have also gotten testcontainers to work this morning.
