### ISSUE TITLE
Upgrade to testcontainers 1.16.0

### ISSUE THREAD

**Issue by mdotson** [testcontainers/testcontainers-scala#195]
It looks like Mac users get Ryuk issues with 1.15.3 (the version that's on current release branch): https://stackoverflow.com/a/69074370/13104708

Could we upgrade testcontainers to 1.16.0 @dimafeng ?

**Comment by dimafeng** [comment]
Hi @mdotson, there are problems with 1.16.0 - https://github.com/testcontainers/testcontainers-scala/pull/190 
Would you like to try to figure out how to solve it?
