### ISSUE TITLE
Image pull policy not applied in GenericContainer

### ISSUE THREAD

**Issue by dzx11** [testcontainers/testcontainers-scala#197]
Hi, it seems that imagePullPolicy is not being used when creating a new GenericContainer. Is it possible for this to get fixed? Or is there something I'm missing here? 
https://github.com/testcontainers/testcontainers-scala/blob/5b26c3b8e5f06ef8d13339fbe49ad7c6d69c02ef/core/src/main/scala/com/dimafeng/testcontainers/GenericContainer.scala#L80

**Comment by LMnet** [comment]
Hi @dzx11 

Thanks for the report. Would you mind creating a pull request? It looks like a straightforward issue.
