### ISSUE TITLE
Upgrade to latest testcontainers version

### ISSUE THREAD

**Issue by natevecc** [testcontainers/testcontainers-scala#2]
The version of testcontainers this is using is behind by a few versions and I'd like to upgrade it to the most recent version. I'll try and do it on my own when I have some free time but any direction and guidance would be really appreciated.

**Comment by dimafeng** [comment]
@natevecc Sorry for not updating the version for a while. I'll be able to do it later today.

If you would like to help me with it, you can do the following:
1) Update the version of TestConteiners in https://github.com/testcontainers/testcontainers-scala/blob/master/gradle.properties
2) Run `./gradlew clean -Pscala=2.11.8 test integrationTest` and `./gradlew clean -Pscala=2.12.1 test integrationTest`
3) if it passes all the tests, I'll be able to release the new version today.

**Comment by natevecc** [comment]
Quick update: tests were initially failing because of this [bug](https://github.com/testcontainers/testcontainers-java/issues/293) which is caused by [this](https://github.com/docker-java/docker-java/issues/806). However once I manually pulled the images needed by the tests, commented out the offending config file, then ran the tests everything passed. I'll put up a PR for this soon.

**Comment by dimafeng** [comment]
@natevecc thank you for your contribution. I'm going to release the new version soon.
