### ISSUE TITLE
ContainerLaunchException with Docker Compose V2

### ISSUE THREAD

**Issue by cuong-dang** [testcontainers/testcontainers-scala#200]
I encountered the following error for `sbt test`.
```
org.testcontainers.containers.ContainerLaunchException: Local Docker Compose exited abnormally with code 1 whilst running command: up -d
```
Solved by unchecking the option Use Docker Compose V2 in Docker General settings.

**Comment by drewboardman** [comment]
I'm also seeing this issue, but downgrading the version of `docker-compose` didn't fix the problem.

**Comment by hosnimed** [comment]
Same problem for me despite downgrading docker-compose version from V3 -> V2.
It succeeds in local test with sbt, but needs to do the docker compose manually before the first launch.
The problem remains in Jenkins CI, any suggestions please?

**Comment by necosta** [comment]
I believe the issue has been solved with the above change. Please review.

**Comment by pan3793** [comment]
@dimafeng Do you have a plan to release 0.40.7?

**Comment by dimafeng** [comment]
Sorry for the delay. Just released

**Comment by dimafeng** [comment]
@pan3793 I can take a look this weekend. If you happen to have some time to submit a PR earlier, I'd really appreciate it.

**Comment by pan3793** [comment]
@dimafeng Thanks, not too urgent on my side, I temporarily created a `docker-compose` script to simulate the V1 compose as a workaround, it works well for a while.

```
~/bin$ cat docker-compose
#/usr/bin/env bash
docker compose $@
```

**Comment by dimafeng** [comment]
Sorry, the version upgrade did go smoothly https://github.com/testcontainers/testcontainers-scala/pull/258. I need somebody to figure out the problem.
