### ISSUE TITLE
Missing `withFileSystemBind` in `GenericContainer`

### ISSUE THREAD

**Issue by benkio** [testcontainers/testcontainers-scala#205]
Hi there,
I'm trying to use a `GenericContainer`, move jar on it, run the command etc etc 
Then I wish to get the output result of such a command that writes on a specific container's path. On `testcontainers-java` I see that the `GenericContainer` has `withFileSystemBind` method that links a host's directory to a container's one.
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L1001

I was expecting to find it in the repo as the `classpathResourceMapping` parameter is exposed in the constructor, but found none.
Do you think is worth adding it? It should be easy and a mirror of the `classpathResourceMapping`
Cheers

**Comment by dimafeng** [comment]
Yes, it's definitely worth adding. I'd really appreciate if you submit a PR with that fix.
