### ISSUE TITLE
Package group is not the same as testcontainers-java

### ISSUE THREAD

**Issue by amdelamar** [testcontainers/testcontainers-scala#22]
Noticed the group `com.dimafeng` is still used, while the java lib is using group `org.testcontainers`.

Tried searching for the scala lib in the group as well. https://search.maven.org/#search%7Cga%7C1%7Corg.testcontainers

Are there any plans to publish the scala lib under the same GroupID as the java lib?

**Comment by dimafeng** [comment]
Hi @amdelamar,

Are you experiencing any problems with current group naming?

**Comment by amdelamar** [comment]
It gives the impression this Scala project is not part of the Testcontainers organization. It would be nice to put all Testcontainers projects under the same GroupID.

**Comment by dimafeng** [comment]
@amdelamar thank you for your feedback. Unfortunately, there is no easy way to move this project to `org.testcontainers`. I'm working toward this goal but not sure that it will happen any time soon.

**Comment by bsideup** [comment]
@dimafeng actually, there is, with Bintray :)
