### ISSUE TITLE
MySQLContainer Random Port

### ISSUE THREAD

**Issue by benkio** [testcontainers/testcontainers-scala#232]
Hi,
I write because, while trying to set up an Integration test with `MySQLContainer`, I noticed the port used is always random instead of the standard `3306`. I attach a screenshot, in this case the random port assigned is `55040`, here is the link to the code:

https://github.com/benkio/myTelegramBot/blob/ca5ee6db33455b65d3a49ebc70ab10ebbbd64d7f/botDB/src/it/scala/com/benkio/botDB/ITSpec.scala

Thanks in advance

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/4698396/179406160-734629cf-7388-46ce-80fc-b6226622cd8d.png">

**Comment by benkio** [comment]
I've just found a workaround by dynamically setting the DB Port via Environment Variable:
https://github.com/benkio/myTelegramBot/commit/67b57585c136a303b9d12511e0f1ad2a1ce177d8

**Comment by LMnet** [comment]
@benkio it's not a bug, it's an intended behavior: https://www.testcontainers.org/features/networking/
```
From the host's perspective Testcontainers actually exposes this on a random free port. This is by design, to avoid port collisions that may arise with locally running software or in between parallel test runs.
```

**Comment by benkio** [comment]
Then I guess my solution is not actually a workaround, but rather the way to go.
I Close the issue
