### ISSUE TITLE
NoClassDefFoundError: munit/Test since 0.40.15

### ISSUE THREAD

**Issue by rtjfarrimond** [testcontainers/testcontainers-scala#255]
I have a project that has been using version `0.40.14` for `testcontainers-scala-munit` and `testcontainers-scala-postgresql`. Recently scala-steward raised a PR to increase the version to `0.40.17` which caused a CI build failure; there are no other changes in the PR other than the version bump. I have tested back to `0.40.15` and seen the same issue for each version.

The error that I am seeing is `java.lang.NoClassDefFoundError: munit/Test`. The compiler suggests trying to use `ClassLoaderLayeringStrategy.Flat`, but that has not helped. When I switch the version back to `0.40.14` the issue is fixed.

**Comment by bannopeter** [comment]
Try using Munit `1.0.0-M8` with `0.40.15+`

**Comment by rtjfarrimond** [comment]
Thanks, that does get over that error! Unfortunately we also depend on `munit-cats-effect`, which does not seem to have a fix out yet. This issue does seem to be resolved though so happy to close. Thank you!
