### ISSUE TITLE
Example Dockerfile usage

### ISSUE THREAD

**Issue by miketwo** [testcontainers/testcontainers-scala#26]
I'm trying to use a Dockerfile with GenericContainer, but can't seem to get it to work. The unit test shows it using `.withFileFromClasspath()`, but my Dockerfile is not on the classpath. I tried `.withFileFromFile()`, but it errors out with something like:
```
{"message":"No such image: testcontainers/b3ewhisadljlsccu:latest"}
```

Are the other `.withFileFromXXX()`'s supported?

**Comment by dimafeng** [comment]
Hi @miketwo 

All `.withFileFromXXX()` methods should work. Since they are coming from the parent Java lib, If they don't, most probably the problem is in upstream library.

Could you please share more detailed code snippet with the paths you pass to  .withFileFromFile()
