### ISSUE TITLE
0.41.0: org.testcontainers.containers.ContainerLaunchException: Container startup failed for image alpine/socat:1.7.4.3-r0

### ISSUE THREAD

**Issue by longliveenduro** [testcontainers/testcontainers-scala#262]
I get "org.testcontainers.containers.ContainerLaunchException: Container startup failed for image alpine/socat:1.7.4.3-r0" when I use 0.41.0.

Works perfect when I switch back to 0.40.17.

Logs are not really saying  much:

"
11:35:11.408 [zio-default-blocking-1] INFO  tc.alpine/socat:1.7.4.3-r0 - Creating container for image: alpine/socat:1.7.4.3-r0
11:35:11.420 [zio-default-blocking-1] ERROR tc.alpine/socat:1.7.4.3-r0 - Could not start container
"

**Comment by Prillan** [comment]
I'm also seeing this for 0.41.0.

**Comment by dzanot** [comment]
Do your compose containers contain the `-`? I saw this, and mine did, but fixed when I removed them.

example:
```yaml
services:
  app-2:
    ...
```
becomes:
```yaml
services:
  app2:
    ...
```

with a corresponding update in the test:

```scala
 ExposedService("app-2", 9130, Wait.forListeningPort())
```
becomes

```scala
 ExposedService("app2", 9130, Wait.forListeningPort())
```

**Comment by longliveenduro** [comment]
Thanks for the hint @dzanot. I tried your suggestion, but still got the same error. Switched back to 0.40.17 with your proposed changes, and there it works So i made no mistake by removing the minus character from service names.

**Comment by dzanot** [comment]
Dang sorry it didn't work. I landed there by watching the docker container start in docker desktop, it was named `app-2-1` and when I explicitly put that as service name in the test it worked. Then after i just tried dropping the `-` altogether.

**Comment by dzanot** [comment]
@longliveenduro we just ran into this again when a `dockerCompose.container.withOptions("--compatibility")` snuck into our config. This flag is no longer supported with the `docker-compose` -> `docker compose` transition of testcontainers `0.41.0`

**Comment by longliveenduro** [comment]
@dzanot Thanks, but I don't use "--compatibility" in my test.

**Comment by longliveenduro** [comment]
@dzanot My fault, just took some time to dive into compose v2, and migrated my test. Works now!

**Comment by skisel-bt** [comment]
It took me a while to learn that the interface has changed for `getServiceHost` and `getServicePort` to accept not the `servicename_1` as before, but `servicename`, so not about `-` character but also `_`
