### ISSUE TITLE
Unable to pull from private Google Container Registry (gcr)

### ISSUE THREAD

**Issue by mrtnrdl** [testcontainers/testcontainers-scala#27]
I'm trying to pull from a private registry in the google cloud with testcontainers. Up until now, I've used short-lived credentials generated via `gcloud docker -a` and it worked flawlessly. 
For docker versions > 18.03, this has been deprecated. 

I'm now trying to move to use gcloud as a credential helper for docker (according to the documentation [here](https://cloud.google.com/sdk/gcloud/reference/auth/configure-docker)). 
This does not work, because when I do not yet have the image locally, it fails to pull it from the registry with the following exception: 

`org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=eu.gcr.io/projectName/gcloud-emulators-datastore:latest)`

When i manually `docker pull eu.gcr.io/projectName/gcloud-emulators-datastore:latest` it works without the need to do any more authentication etc, because I'm already authenticated via gcloud.

**Comment by dimafeng** [comment]
Hi @mrtnrdl,
Sorry, I don't have any experience with gcloud. Most probably, this problem is  common for the parent project (testcontainers-java) as well. I would recommend to create an issue in https://github.com/testcontainers/testcontainers-java or ask in https://testcontainers.slack.com

**Comment by dimafeng** [comment]
Please reopen the issue if you find out that the problem is scala implementation specific.

**Comment by mrtnrdl** [comment]
Thanks for the quick reply - I'll raise it with the parent project. Thanks! And keep up the good work 👍
