### ISSUE TITLE
Wrong readme file content for FixedHostPortGenericContainer

### ISSUE THREAD

**Issue by SimoneCafiero** [testcontainers/testcontainers-scala#29]
Within the readme file rather than **FixedHostPortGenericContainer**, **FixedHostPortGenericGenericContainer** (with the typo) is used.

> Fixed Host Port Containers
> This container will allow you to map container ports to statically defined ports on the docker host.
> 
> ...
> val container = FixedHostPortGenericGenericContainer("nginx:latest",
>     waitStrategy = Wait.forHttp("/"),
>     exposedHostPort = 8090,
>     exposedContainerPort = 80
>   )

**Comment by dimafeng** [comment]
@SimoneCafiero thank you! I've fixed that.
