### ISSUE TITLE
Set Host-/Containername

### ISSUE THREAD

**Issue by BirgerK** [testcontainers/testcontainers-scala#36]
Hi there,

in the testcontainers-java you're able to set nearly any parameters by using the underlying Docker-API: https://www.testcontainers.org/usage/options.html#customizing-the-container
I didn't get this API working with this Scala-Library.  Have you any examples to get this working? Or is it even not implemented?

Thank you
Birger

**Comment by dimafeng** [comment]
Hi @BirgerK ,

You can use `configure` to modify underlying container.
For example:
```
override val container = PostgreSQLContainer().configure(_.withCreateContainerCmdModifier((cmd: CreateContainerCmd) => cmd.withMemory((4 * 1024 * 1024).toLong)))
```
