### ISSUE TITLE
Shading issue with javax

### ISSUE THREAD

**Issue by rnehruDDUK** [testcontainers/testcontainers-scala#4]
Hi, I have pulled the following dependency with sbt successfully:
"com.dimafeng" % "testcontainers-scala_2.12" % "0.6.0",

However upon running my unit tests, I am seeing the following errors in compiling when trying to run my scalatest specs:

Error:scalac: Class org.testcontainers.shaded.javax.annotation.CheckForNull not found - continuing with a stub.

**Comment by dimafeng** [comment]
Hi,
Could you please share a code snippet of the spec that can't be compiled?

**Comment by rnehruDDUK** [comment]
Well I have just started playing around with the framework so far. Please find my example spec below.

I have just read the docs and switched to using 
`"com.dimafeng" %% "testcontainers-scala" % "0.6.0" % "test"` as I am using Scala 2.11 and am still seeing the same issue.



`import java.sql.DriverManager

import com.dimafeng.testcontainers.{MySQLContainer, ForEachTestContainer}
import org.scalatest.{Matchers, WordSpec}
import utils.Mocking

class CatalogueIntegrationSpec extends WordSpec with Mocking with Matchers with ForEachTestContainer {

  override val container = new MySQLContainer()
  Class.forName(container.driverClassName)
  val connection = DriverManager.getConnection(container.jdbcUrl, container.username, container.password)


  "new catalogue" should {
    "write new item into db" in {
      val query = connection.prepareStatement("SELECT 1").executeQuery()
      query.next()
      query.getInt(1) should be (1)

    }
  }


}`

**Comment by rnehruDDUK** [comment]
Also, is there a future roadmap for adding Postgres support for testcontainers-scala?

**Comment by dimafeng** [comment]
@rnehruDDUK 
It seems you also need to add "org.testcontainers" % "mysql" % "1.2.1" in order to use MySQLContainer.

---

> Also, is there a future roadmap for adding Postgres support for testcontainers-scala?

This can be achieved by:
1) submitting a feature request to the [core project](https://github.com/testcontainers/testcontainers-java/issues)
2) using a generic container where you specify your own docker image (see [example](https://github.com/testcontainers/testcontainers-scala/blob/master/src/test/scala/com/dimafeng/testcontainers/integration/GenericContainerSpec.scala))

**Comment by rnorth** [comment]
Re Postgres, it's already in core...

**Comment by dimafeng** [comment]
@rnorth thank you for the information. I'll take a look when I have free time.
