### ISSUE TITLE
Containers in suites where all tests cases are excluded from run by tags are beeing created.

### ISSUE THREAD

**Issue by Vistritium** [testcontainers/testcontainers-scala#41]
When there is scalatest test that is using `ForAllTestContainer` and all test cases inside it are excluded from execution because of tagging rule the container is still beeing setup.
I think it is reasonable to assume that if there are no test cases to be executed the container should not be created.

**Comment by dimafeng** [comment]
Hi @Vistritium,

Do you have a small code snippet that could reproduce the issue?
The behavior that you've explained is implemented in the scope of https://github.com/testcontainers/testcontainers-scala/pull/9, if you provide me with an example I will check why it's not working.

Thank you,
Dmitry

**Comment by Vistritium** [comment]
Please see this minimal project:
https://github.com/Vistritium/testcontainer-scala-tags
The `sbt test` will execute 0 test but the container is created.

**Comment by dimafeng** [comment]
@Vistritium thank you! I'll take a look soon

**Comment by dimafeng** [comment]
@Vistritium 
I ran `test` but it does include the test.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
[info] TheTest:
[info] - will be ignored *** FAILED ***
[info]   org.scalatest.exceptions.TestFailedException was thrown. (TheTest.scala:12)
[info] Run completed in 9 seconds, 379 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error]         testcontainer.scala.tags.TheTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 21 s, completed Feb 18, 2019 9:22:27 AM
```

**Comment by Vistritium** [comment]
Hi @dimafeng,

Sorry I forgot to push one change to `build.sbt`. I have updated the repository. The `sbt test` now produces following result:
```
[info] Loading project definition from /media/sf_work-sources/projects/private/testcontainer-scala-tags/project
[info] Updating ProjectRef(uri("file:/media/sf_work-sources/projects/private/testcontainer-scala-tags/project/"), "testcontainer-scala-tags-build")...
[info] Done updating.
[info] Loading settings for project testcontainer-scala-tags from build.sbt ...
[info] Set current project to testcontainer-scala-tags (in build file:/media/sf_work-sources/projects/private/testcontainer-scala-tags/)
[info] Updating ...
[info] Done updating.
[info] Compiling 1 Scala source and 1 Java source to /media/sf_work-sources/projects/private/testcontainer-scala-tags/target/scala-2.12/test-classes ...
[info] Done compiling.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
[info] TheTest:
[info] Run completed in 6 seconds, 996 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[success] Total time: 21 s, completed Feb 18, 2019 4:37:34 PM
```

**Comment by dimafeng** [comment]
Thanks for the updated code. I checked the code that I mentioned earlier `expectedTestCount(args.filter) == 0` and it works as expected giving 0 as a count. However, the output
```
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space

```
is produced by the container initialization and doesn't start the container (to be 100% correct, it starts `quay.io/testcontainers/ryuk:0.2.2` which monitors running containers). If you want avoid having it, you can define your container as `lazy val`:

```
override lazy val container: Container = PostgreSQLContainer("mdillon/postgis")
```

I'll think about how this behavior can be improved.

**Comment by Vistritium** [comment]
The `lazy val` solution works!
The issue I had was that we have developers working on Windows and Linux and Windows developers don't have docker environment. So it's not possible to start the `testcontainers/ryuk:0.2.2`. The tests needing docker were tagged and ignored on Windows but it was still crashing.
But with the above solution it works.
Thanks!
