### ISSUE TITLE
DockerCompose wait strategy support

### ISSUE THREAD

**Issue by zella** [testcontainers/testcontainers-scala#67]
I not found any methods about it in `com.dimafeng.testcontainers.DockerComposeContainer`. Is there supported? Example will be nice!

**Comment by dimafeng** [comment]
@zella waitStratery is part of `exposedServices` parameter
```
DockerComposeContainer(Seq(new File("src/test/resources/docker-compose.yml")), exposedServices = Seq(ExposedService("redis_1", 6379, waitStrategy=...)))
```
