### ISSUE TITLE
Explicit identifier in DockerComposeContainer constructor

### ISSUE THREAD

**Issue by htch** [testcontainers/testcontainers-scala#8]
Is it an option to add support for these constructors?

https://github.com/testcontainers/testcontainers-java/blob/357d5752a134bc340b1054acedf2eb78f7f24e64/core/src/main/java/org/testcontainers/containers/DockerComposeContainer.java#L86

**Comment by dimafeng** [comment]
Hi @htch,
Yes, I'll take a look tonight. If you already have changes which need to be made, you can submit a pull request to speedup the process :)

**Comment by dimafeng** [comment]
@htch 
`def apply(composeFiles: Seq[File], exposedService: Map[String, Int] = Map())` - does it look like what you're looking for?

**Comment by htch** [comment]
I suppose this is also useful, but I was thinking about `identifier` param in this constructor `public DockerComposeContainer(String identifier, File... composeFiles)`.

**Comment by dimafeng** [comment]
Released in 0.10.0
