### ISSUE TITLE
Symbol 'type org.junit.runner.Description' is missing from the classpath

### ISSUE THREAD

**Issue by aserrallerios** [testcontainers/testcontainers-scala#89]
Hello, just got this error at compilation time from a scalatest suite using `ForAllTestContainer` trait.

The install has been just: 

> "com.dimafeng" %% "testcontainers-scala" % "0.33.0" % "test"

Not sure what to do to fix it. It looks like the junit4 dependency should be included in the tests, but somehow it isn't.

Full error:

```
[error]      Symbol 'type org.junit.runner.Description' is missing from the classpath.
[error]      This symbol is required by 'value com.dimafeng.testcontainers.TestContainers.TestContainersSuite.suiteDescription'.
[error]      Make sure that type Description is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error]      A full rebuild may help if 'TestContainers.class' was compiled against an incompatible version of org.junit.runner.
[error]      L8:   override val container = PostgreSQLContainer()
```

**Comment by LMnet** [comment]
Hi @aserrallerios! Do you have scalatest artifact in your dependencies?

**Comment by aserrallerios** [comment]
Yes, just migrating a mock test to a docker one.

**Comment by LMnet** [comment]
@aserrallerios did you try full rebuild as suggested in the error message? Also, I recommend trying [sbt-dependency-graph](https://github.com/jrudolph/sbt-dependency-graph) to see what's happened with your dependencies.

**Comment by aserrallerios** [comment]
I fixed it updating to the latest `testcontainers-scala` version and removing all my local stuff. Sorry for the false alarm, but it was a crazy error, wasn't it? Thanks again.
