### ISSUE TITLE
SSL Cert Invalid for Slack Invite

### ISSUE THREAD

**Issue by jamesward** [testcontainers/testcontainers-scala#93]
```
$ curl https://slack.testcontainers.org/
curl: (60) SSL: no alternative certificate subject name matches target host name 'slack.testcontainers.org'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by bsideup** [comment]
cc @rnorth

**Comment by jamesward** [comment]
Closed because?  The README still references this URL that does not have a valid cert:
https://github.com/testcontainers/testcontainers-scala/blob/master/README.md

**Comment by dimafeng** [comment]
@jamesward sorry. Slack channel is maintained by testcontainers-java team. It seems that https://slack.testcontainers.org/ has a self-signed cert. I'd recommend to get in touch with @bsideup or @rnorth

**Comment by jamesward** [comment]
Thanks.  @rnorth let me know if you'd like a bug filed elsewhere.
