### ISSUE TITLE
Containers not cleaned up after tests are ran?

### ISSUE THREAD

**Issue by mcguffin0725** [testcontainers/testcontainers-scala#96]
I'm using the docker compose functionality, and after the tests complete I see the dangling containers with `docker ps`.  Is there some kind of cleanup hook I need to call?  I'm running on Mac OSX Mojave, and running the tests through sbt.

**Comment by LMnet** [comment]
testcontainers-scala doesn't provide any specific logic in this aspect and fully rely on the testcontainers-java. As far as I know, all containers should be killed after tests, even if something goes wrong. It's done by the special ryuk container. Testcontainers-java starts it before all tests.

@bsideup could you help, please? Maybe there is some docker-compose specific behavior?

**Comment by Humblehound** [comment]
I've noticed the same behaviour. The docs mention that containers are shutdown on JVM exit, so that explains why running from `sbt` doesn't shut them down (at least in interactive mode). But the issue still exists when they're ran from Intellij or one-off.

**Comment by bsideup** [comment]
@LMnet hard to say without any info provided (TC's version, what's used, `withReuse` or not, etc etc)

**Comment by LMnet** [comment]
@mcguffin0725 @Humblehound can you share minimal reproducible code?

**Comment by Humblehound** [comment]
Sure, I'll try to publish it by tomorrow

pt., 24 sty 2020, 05:32 użytkownik Yuriy Badalyantc <
notifications@github.com> napisał:

**Comment by Humblehound** [comment]
After upgrading `testcontainers-scala` to `0.35.0` and `testcontainers` to `1.12.5` on Scala `2.12.10` with Docker Engine 19.03.5 I'm not longer able to reproduce this issue. Note: it does take a second or two for the containers to shutdown, but they do exit gracefully after the test is done

**Comment by LMnet** [comment]
@mcguffin0725 can you try the same steps as @lmyslinski and report about it?

**Comment by quiquedev** [comment]
im having the same problem. the `ryuk` container doesn't shutdown after running `sbt test`

my versions:
`scala` 2.13.1
`testcontainers-scala` 0.36.1
`scalatest` 3.1.1
`docker` 19.03,8
