### ISSUE TITLE
DockerComposeContainer with "new API"

### ISSUE THREAD

**Issue by JLofgren** [testcontainers/testcontainers-scala#97]
How can I create a ContainerDef for a DockerComposeContainer in the "new API"? 

(Aside: the README says to write on your slack channel with questions, but it appears I need an invitation to log in there.)

**Comment by dimafeng** [comment]
cc @LMnet

**Comment by LMnet** [comment]
@JLofgren thanks for your report! Actually, I forgot to add support of the new API for the `DockerComposeContainer` :sweat_smile: Fixed in #100

About slack — you can find [an invite link](https://slack.testcontainers.org/) in the readme, in the beginning.
